# Generated by Django 3.0.6 on 2020-06-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_description', models.CharField(max_length=255, unique=True)),
                ('home_size', models.CharField(max_length=255, unique=True)),
                ('initial', models.CharField(max_length=15, verbose_name='Initial')),
                ('weekly', models.CharField(max_length=15, verbose_name='Weekly')),
                ('week2', models.CharField(max_length=15, verbose_name='Every 2nd week')),
                ('week3', models.CharField(max_length=15, verbose_name='Every 3rd week')),
                ('monthly', models.CharField(max_length=15, verbose_name='Monthly')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
            },
        ),
    ]
